### PR TITLE
cli: various improvements

### LINKED ISSUE #119: cli: fix account existence checks
in various places we get account and check if its some/none to do things like abort if a pool exists or doesnt. this is wrong because accounts exist if they have nonzero lamports. this is slightly annoying if someone were to send lamports to a designated pool address to waste ten minutes of someones life commenting this check out

the upcoming `command_create_onramp()` in #107 does this better by checking length, do that everywhere

### LINKED ISSUE #143: update readme
no longer "upcoming," has new features, also symlink or whatever is needed to make it show up on crates io

### LINKED ISSUE #234: cli: deposit will create token account even when --dry-run specified
When the --dry-run flag is given, spl-single-pool should only simulate and not actually send transactions.

This logic is enforced in async fn process_transaction() in clients/cli/src/main.rs which is used in most places that create transactions.

However in async fn command_deposit() in clients/cli/src/main.rs, if no token account was designated in the command invocation (command_config.token_account_address), token.get_or_create_associated_account_info() is called which submits a transaction to create the associated token account directly via the rpc client bypassing process_transaction() and its check of config.dry_run.

If the command line tool is invoked with --dry-run the associated token account should *not* be created if it is missing.

### LINKED ISSUE #392: cli: `DisplayAll` is unacceptably slow
fetching from mainnet takes several minutes. we only ever tested this on a local test validator, using it against mainnet sucks. there is obvious low-hanging fruit:
1) `get_minimum_pool_balance()` is called for every stake account. call it once
2)  batch all stake account fetches into one `getMultipleAccounts` call
3) possibly batch the token mint calls. we currently fetch with `getTokenSupply` though which is presumably cheaper than getting all their account datas. maybe it would be best to get the supplies like we do, but with some bounded concurrency so we are always fetching 10 at a time or something

presently there are ~50 mainnet svsp pools. we currently do ~150 rpc calls. fix 1 gets us to ~100, fix 2 gets us to ~50. do those then worry about the tokens after

edit: nevermind. 1 is easy. the solution to 2 and 3 is two `getMultipleAccounts` calls

edit2: note to self that `getMultipleAccounts` take a maximum for 100 so i need to properly chunk these

### PR DESCRIPTION
**Pull request by 2501babe**
* `display --all` now performs 4 total rpc calls total instead of 1 + (3 * number of pools)
* determine if accounts are initialized based on their data rather than lamports
* show main stake account excess lamports in `display --verbose`
* do not create an associated token account for `deposit --dry-run`
* correctly print that we cannot display deposit/withdraw values for `--dry-run`
* check a vote-owned account is actually a vote account for `initialize`
* remove `ProgramClient` from tests
* add test for `display --all`
* update README.md

part of #118 
closes #119 
closes #143 
closes #234 
closes #392

### CODE REVIEW

File: clients/cli/src/main.rs [hunk 1]
```diff
@@ -793,28 +776,79 @@ async fn command_display(config: &Config, command_config: DisplayCli) -> Command
...
+        )]
+    };
+
+    if pool_and_vote_addresses.len() > 100 {
+        return Err(
+            "Displaying more than 100 pools is not implemented; if you see \
+            this error, feel free to open an issue in the SVSP repo."
+                .into(),
+        );
+    }
```
Comment (2501babe) [inline clients/cli/src/main.rs]: `getMultipleAccounts` limit. mainnet has 40-something pools, so it wont be relevant for awhile. ill probably do the >100 chuncking and the onramp support in display at the same time, the two of them will make it complicated enough ill refactor all this stuff into its own module

File: clients/cli/tests/test.rs [hunk 2]
```diff
@@ -55,11 +53,10 @@ async fn setup(raise_minimum_delegation: bool, initialize_pool: bool) -> Env {
...
-    // make clients
-    let rpc_client = Arc::new(validator.get_async_rpc_client());
-    let program_client: PClient = Arc::new(ProgramRpcClient::new(
-        rpc_client.clone(),
-        ProgramRpcClientSendTransaction,
+    // make client
+    let rpc_client = Arc::new(RpcClient::new_with_commitment(
+        validator.rpc_url(),
+        CommitmentConfig::confirmed(),
     ));
```
Comment (2501babe) [inline clients/cli/tests/test.rs]: removed `ProgramClient` from tests just because we dont need it. planning on dropping token client from the cli itself when i do the 3.0 upgrade

File: clients/cli/tests/test.rs [hunk 3]
```diff
@@ -142,7 +129,7 @@ async fn wait_for_next_epoch(rpc_client: &RpcClient) -> Epoch {
     println!("current epoch {}, advancing to next...", current_epoch);
     loop {
         let epoch_info = rpc_client.get_epoch_info().await.unwrap();
-        if epoch_info.epoch > current_epoch {
+        if epoch_info.epoch > current_epoch && epoch_info.slot_index > 0 {
             return epoch_info.epoch;
         }
```
Comment (2501babe) [inline clients/cli/tests/test.rs]: this was a frustrating but ultimately funny debugging experience, i was going nuts trying to figure out how my `command_deposit()` refactor introduced stake program error 10 (`VoteAddressMismatch`) in some tests and it took longer than id like to admit to notice it was actually error 0x10 (`EpochRewardsActive`)

i think something i changed made it slightly _faster_: before, by time the test transaction executed, a slot had already elapsed

File: README.md [hunk 4]
```diff
@@ -1,9 +1,52 @@
...
+The BPF program deployed on all clusters is built with [solana-verify](https://solana.com/developers/guides/advanced/verified-builds). It may be verified independently by comparing the output of:
+
+```console
+solana-verify get-program-hash -um SVSPxpvHdN29nkVg9rPapPNDddN5DipNLRUFhyjFThE
+```
+
+with:
+
+```console
+solana-verify build --library-name program
```
Comment (joncinque) [inline README.md]: It looks like the build works with this command, but in my testing and looking at the source code, I think `--library-name` takes the crate name:
```suggestion
solana-verify build --library-name spl_single_pool
```

**Review by joncinque — DISMISSED** [review]
Looks great to me! Just some tiny nits which you can take, leave, or fix in another PR

File: clients/cli/tests/test.rs [hunk 5]
```diff
@@ -470,6 +483,41 @@ async fn display() {
...
+        .output()
+        .unwrap();
+    assert!(output.status.success());
+
+    let stdout = String::from_utf8_lossy(&output.stdout);
+    let pools = stdout
+        .lines()
+        .filter(|line| line.starts_with("  Pool address:"))
+        .count();
+    assert_eq!(pools, 3);
```
[the remark this answers is not in the document]
Comment (2501babe) [reply clients/cli/tests/test.rs]: [2a1316d](https://github.com/solana-program/single-pool/pull/393/commits/2a1316dcb4bf2e31147191894a7de34e58d84c3b)
